### PR TITLE
set up file structure, install riverpod lib

### PR DESCRIPTION
**Pull request by Amarin-AMR**

### CODE REVIEW

**Review by ribbinpo — COMMENTED** [review]
- what is the difference between the base and widget folders???
- why is the model folder in global ??
- I think we don't need to separate riverpod because riverpod combines ViewModel

**Comment by Amarin-AMR** [comment]
- Base made for base_screen (display) and base_viewmodel (logic) but widget folders made for components which use many times.
- model folder inside it contains data model which attributes of a specific type of data to suitable with JSON (API response)
- okay

**Comment by ribbinpo** [comment]
I understand your purpose, but model folders in my suggestion should move to base folder because it is reuse resource then specific model also has in each feature folder

**Comment by Amarin-AMR** [comment]
okay, now I change it inside features to categorize in each features to be MVVM (model, view, view model)

**Review by ribbinpo — APPROVED** [review]

**Pull request merged**
